name: "Prochy's Webhook"
guid: "7794e0a2-19d1-4b0e-b888-deacf1647e3e"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-webhook.png"
version: 14
targetAbi: "10.9.1.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Sends notifications."
description: >
  Sends notifications to destinations via webhooks.

category: "Notifications"
artifacts:
  - "Jellyfin.Plugin.Webhook.dll"
  - "Handlebars.dll"
  - "MailKit.dll"
  - "MimeKit.dll"
  - "BouncyCastle.Cryptography.dll"
  - "MQTTnet.dll"
  - "MQTTnet.Extensions.ManagedClient.dll"
changelog: |2-
  ### Bug Fixes ###
  - Fix AuthenticationFailureNotifier, AuthenticationSuccessNotifier (#238) @crobibero
  - Actually register hosted services (#233) @crobibero

  ### Dependency updates ###
  - chore(deps): update dependency mqttnet.extensions.managedclient to v4.3.4.1084 (#187) @renovate
